name: catt_catt
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animated_notch_bottom_bar: ^1.0.1
  auto_route: ^7.8.4
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  device_preview: ^1.1.0
  firebase_analytics: ^10.8.7
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  flash: ^3.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  geolocator: ^11.0.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.10
  intl: ^0.18.1
  mask_text_input_formatter: ^2.9.0
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.1.2
  riverpod: ^2.5.1
  slang: ^3.30.1
  slang_flutter: ^3.30.0
  upgrader: ^10.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  slang_build_runner: ^3.30.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
