name: catt_catt
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animated_notch_bottom_bar: ^1.0.3
  auto_route: ^8.1.3
  cached_network_image: ^3.3.1
  chips_choice: ^3.0.1
  cloud_firestore: ^4.17.5
  connectivity_plus: ^6.0.3
  country_picker: ^2.0.26
  device_preview: ^1.1.0
  firebase_analytics: ^10.10.7
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7
  flash: ^3.1.0
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.1
  flutter_form_builder: ^9.2.1
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^10.0.1
  freezed_annotation: ^2.4.1
  geolocator: ^12.0.0
  google_mlkit_face_detection: ^0.11.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  mask_text_input_formatter: ^2.9.0
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.1.3
  riverpod: ^2.5.1
  salomon_bottom_bar: ^3.3.2
  slang: ^3.31.0
  slang_flutter: ^3.31.0
  upgrader: ^10.3.0
  url_launcher: ^6.2.6

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  slang_build_runner: ^3.31.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
