name: catt_catt
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animated_notch_bottom_bar: ^1.0.3
  auto_route: ^8.2.0
  cached_network_image: ^3.3.1
  chips_choice: ^3.0.1
  cloud_firestore: ^5.0.1
  collection: ^1.18.0
  connectivity_plus: ^6.0.3
  country_picker: ^2.0.26
  dart_firebase_admin: ^0.3.1
  firebase_analytics: ^11.0.1
  firebase_app_check: ^0.3.0+1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_crashlytics: ^4.0.1
  firebase_messaging: ^15.0.1
  firebase_storage: ^12.0.1
  flash: ^3.1.0
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.1
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.14
  flutter_firebase_chat_core: ^1.6.8
  flutter_form_builder: ^9.3.0
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_sound: ^9.6.0
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^10.0.1
  freezed_annotation: ^2.4.1
  geolocator: ^12.0.0
  google_mlkit_face_detection: ^0.11.0
  google_mobile_ads: ^5.1.0
  googleapis_auth: ^1.6.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  lottie: ^3.1.2
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  purchases_flutter: ^6.29.4
  purchases_ui_flutter: ^6.29.4
  riverpod_annotation: ^2.3.5
  rxdart: ^0.27.0
  slang: ^3.31.0
  slang_flutter: ^3.31.0
  smooth_sheets: ^0.8.1
  syncfusion_flutter_sliders: ^26.1.39
  url_launcher: ^6.3.0
  video_player: ^2.8.7

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  slang_build_runner: ^3.31.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "assets/images/logo-background.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
    - key.json
